version: '3'
 
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/code/staticfiles
    restart: always
    ports:
      - "5000:5000"
    networks:
      - web_nw
      - nginx_nw
  nginx:
      container_name: nginx
      build:
        context: nginx/
        dockerfile: Dockerfile
      ports:
        - "80:80"
      volumes:
        - static:/code/staticfiles
      networks:
        - nginx_nw
volumes:
  static:
    external: true
networks:
  web_nw:
    external: true
  nginx_nw:
    external: true